### ISSUE TITLE
Unable to decrypt file when ansible-value is installed in virtual environment.

### ISSUE THREAD

**Issue by ppluciennik** [dhoeric/vscode-ansible-vault#1]
Ability to control path to ansible-vault would be nice.

**Comment by dhoeric** [comment]
Thanks for your comment @ppluciennik, it's updated to vscode marketplace :)

**Comment by ppluciennik** [comment]
To be honest you shouldn't set binpath to /usr/local/bin as ansible-vault may be located somewhere else. I'd rather define ansibleVault.executable to "ansible-vault" and then use it in source code.
This way it will work as before and configurable setting that can be overloaded by the user.

**Comment by dhoeric** [comment]
That's updated to `0.0.4`

**Comment by ppluciennik** [comment]
Default value in settings should be:
"default": "ansible-vault"

Current value will not work on computers where ansible-vault is located somewhere else.
"default": "/usr/local/bin/ansible-vault" - that's incorrect.

**Comment by dhoeric** [comment]
Thanks anyway for your comment, updated.
