### ISSUE TITLE
vault password file not found

### ISSUE THREAD

**Issue by Dutchy-** [dhoeric/vscode-ansible-vault#11]
I get the following error:

```
'.vault_password' specified in defaults.vault_password_file of '/Users/dutchy/path/to/project/here/ansible.cfg' is not exist.
```

This file is specified as follows:

```
[defaults]
inventory=./inventory.ini
vault_password_file=.vault_password
```

Maybe some error with relative paths?

This is on MacOS, if that is relevant.

**Comment by codestation** [comment]
Same problem on Linux (openSUSE Tumbleweed), using the latest VSCode (1.20). Using ansible-vault from command line works as expected and finds the password file.

**Comment by dhoeric** [comment]
Thanks for reporting, error is due to unspecified working directory when running `ansible-vault`.
The fix is published to `0.1.1` from marketplace.

@Dutchy- @codestation Please help to check if it works on your side 😄

**Comment by codestation** [comment]
Yes, now works fine for me in single-dir workspaces.

**Comment by Dutchy-** [comment]
Thanks @dhoeric , this issue is now fixed! As @codestation says, for single-dir workspaces anyway, I'll comment in the other issue.
