### ISSUE TITLE
Error when decrypting file

### ISSUE THREAD

**Issue by marcelhekking** [dhoeric/vscode-ansible-vault#15]
When I try to decrypt a file I get the following error: filepath.charCodeAt is not a function

**Comment by dhoeric** [comment]
May I know some background information on the issue?

- Operation system you're using
- Version of vscode
- Version of the plugin
- Method of saving the vault-password
- Path of the encrypt/decrypt file
- any things you might think related

**Comment by marcelhekking** [comment]
Of course:
- OS: Ubuntu 17.10
- vscode: 1.20.1
- plugin: 0.1.2
- method of saving: via keypass in settings
- path of encrypt/decrypt: don't know what you mean. It's just a normal Linux file path. I think i'ts not in the path itself. I have two separate repo's and both are giving me the same errors with different filepaths.

**Comment by marcelhekking** [comment]
Any findings yet?

**Comment by dhoeric** [comment]
Fixed by #19

**Comment by dhoeric** [comment]
It's been released as 0.1.3, can be upgraded from VS Code itself!

Thanks again for the contribution.
