### ISSUE TITLE
Extention v.0.0.5 not work in VS Code.

### ISSUE THREAD

**Issue by Nklya** [dhoeric/vscode-ansible-vault#3]
Hello.

I faced a problem with ansible-vault extention.
It not work. I set all three variables in settings, restart VS code.
When i select Encrypt/decrypt in menu i got nothing.

My environment:
* OS: MacOS 10.12.4 and Debian 9
* Ansible: 2.3.0.0 (installed from brew and pip)
* VS Code: 1.11.2
* Extention: v.0.0.5

**Comment by dhoeric** [comment]
Hi @Nklya, thanks for your report.
Usually, you don't need to define `keyfile`  when `keypass` is already here.

Is the ansible-vault installed in MacOS or debian instead?

**Comment by Nklya** [comment]
Hello.

> Usually, you don't need to define keyfile when keypass is already here.

Now I defined only path an password with no luck, extention don't work.

> Is the ansible-vault installed in MacOS or debian instead?

ansible-vault installed in both MacOS and debian.

**Current settings:**
"ansibleVault.executable": "/usr/local/bin/ansible-lint",
"ansibleVault.keypass": "qwer"

**Comment by dhoeric** [comment]
Just wonder, `ansible-lint`is also for file encryption/decryption?

**Comment by Nklya** [comment]
> Just wonder, ansible-lintis also for file encryption/decryption?

Yes, i made typo writing to issue.

Settings in VS Code correct:
    "ansibleVault.executable": "/usr/local/bin/ansible-vault",
    "ansibleVault.keypass": "qwer"

**Comment by Nklya** [comment]
I've found why extension not work.

It not work if file placed not in root folder of project.

For example:
├── 1
│   └── not_work.yml
└── work.yml

**Comment by dhoeric** [comment]
May I know the name of the folder?

**Comment by Nklya** [comment]
My previous guess was wrong.

I digged more and make example repo with desription here : https://github.com/Nklya/vault-test

I've found that extention not work when word 'ansible' is in directory name and with spaces in directory name.

**Comment by dhoeric** [comment]
0.0.6 should have fix the issue on file path with whitespace.

and it's pretty sure that the hotkey is not pretty work somehow,  
could you try with <kbd>cmd+shift+p</kbd> then `Encrypt/Decrypt with ansible-vault`?

**Comment by Nklya** [comment]
> and it's pretty sure that the hotkey is not pretty work somehow,
could you try with cmd+shift+p then Encrypt/Decrypt with ansible-vault?

I always check both hotkey and "Encrypt/Decrypt with ansible-vault" when do testing.
Result is the same.

> 0.0.6 should have fix the issue on file path with whitespace.

Yes, 0.0.6 fix issue with spaces, thanks.

**Comment by dhoeric** [comment]
Seems the problem not that trivial, would you mind to continue the conversion in gitter or whatever channel you like?

**Comment by Nklya** [comment]
Ok, I wrote a message to you in Gitter.

**Comment by dhoeric** [comment]
Found that's related to `doc.languageId` on `ansible` while setting the file-association to ansible in 
https://marketplace.visualstudio.com/items?itemName=haaaad.ansible

Made a fix on #6

**Comment by Nklya** [comment]
Yeah, it work now.
Thanks.
