### ISSUE TITLE
Files without .yml extenstion

### ISSUE THREAD

**Issue by xdfil** [dhoeric/vscode-ansible-vault#5]
I'm not able to encrypt files that do not have a .yml extension. Can we lift this restriction somehow?

**Comment by dhoeric** [comment]
Basically you can define the file to `YAML` or `ansible` (with https://marketplace.visualstudio.com/items?itemName=haaaad.ansible)

Would you mind to share your use case?

**Comment by excalq** [comment]
Ansible-vault can encrypt entire files, as opposed to values in a .yml file. A common use case is encrypting SSL private keys. I don't think this section is necessary:
```
        if ( ! (doc.languageId == "yaml" || doc.languageId == "ansible") ) {
            vscode.window.showErrorMessage(`ansible-vaule: Only parse file with Language Mode: "YAML", "ansible"`);
            return;
        }
```

**Comment by dhoeric** [comment]
Seems like a pretty common scenario to encrypt/decrypt file with any types.  
Updated on #7

**Comment by dhoeric** [comment]
@xdaxdb @excalq Thanks for your advices, #7 removed the restriction!
