### ISSUE TITLE
Feature Request: Support vault_password_file via ansible.cfg

### ISSUE THREAD

**Issue by mdlnr** [dhoeric/vscode-ansible-vault#9]
When using an `ansible.cfg` file which contains a setting for a default `vault_password_file` the extension always asks for a password. Leaving this empty will result in an error.

- The extension should check if the` ansible.cfg` contains a default setting for a `vault_password_file`
- The file referenced in `ansible.cfg` can be defined with an absolute path or relative to the location of the `ansible.cfg`
- The extension should not ask for a password when the setting is defined in `ansible.cfg` and the referenced file exists 

---
Ref: http://docs.ansible.com/ansible/latest/intro_configuration.html#configuration-file

**Comment by codeflows** [comment]
@tjacoby I've written [another ansible-vault plugin](https://github.com/codeflows/vaulty) for viewing vaults that resolves the password in the way you've described. It does not support editing yet, so for that vscode-ansible-vault is the way to go :)

**Comment by dhoeric** [comment]
@tjacoby That's absolutely is a nice feature but I haven't worked on this project for a while.
Need a bit of time to setup the env thingy. Will implement it very soon 👍

**Comment by dhoeric** [comment]
@tjacoby I've published `0.1.0` on VSCode marketplace, could you test on it? Thanks!

**Comment by mdlnr** [comment]
Hi @dhoeric - Thats awesome. Thanks for adding this request. I tested it with my project and it works fine. 👍

**Comment by dhoeric** [comment]
Good to hear this 😄
